package View.GUI;

import Controller.CollectionControl;
import Controller.Controller;
import Model.Collection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * represent for delete collection dialog
 *
 * @author Nguyễn Đức Thắng
 */
public class DeleteCollectionDialog extends javax.swing.JFrame {

    // main controller of this application
    private Controller mainController;
    // controller of collections
    private CollectionControl collectionCotroller;
    // selected collection
    private Collection selectedCollection;

    /**
     * Creates new form DeleteCollectionDialog
     */
    public DeleteCollectionDialog(Controller controller) {
        this.mainController = controller;
        this.collectionCotroller = controller.getCollectionController();
        initComponents();
        initCollections();
        setIcon();
    }

    /**
     * initial collections
     */
    public void initCollections() {
        this.selectedCollection = null;
        for (Collection col : collectionCotroller.getAllCollection()) {
            jCollections.addItem(col);
        }
        selectedCollection = jCollections.getItemAt(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDeleteCollection = new javax.swing.JButton();
        jCancelDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCollections = new javax.swing.JComboBox<>();

        setTitle("Delete Collection");

        jDeleteCollection.setText("Delete");
        jDeleteCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteCollectionActionPerformed(evt);
            }
        });

        jCancelDelete.setText("Cancel");
        jCancelDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Collection:");

        jCollections.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDeleteCollection, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jCancelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCollections, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCollections, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDeleteCollection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCancelDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * event when delete button clicked
     *
     * @param evt event fired
     */
    private void jDeleteCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteCollectionActionPerformed
        this.selectedCollection = (Collection) jCollections.getSelectedItem();

        if (collectionCotroller.deleteCollection(selectedCollection)) {
            JOptionPane.showMessageDialog(null, "Xóa collection thành công.", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Xóa collection thất bại.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        mainController.updateView();
        this.setVisible(false);
    }//GEN-LAST:event_jDeleteCollectionActionPerformed

    /**
     * event when cancel button clicked
     *
     * @param evt event fired
     */
    private void jCancelDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelDeleteActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jCancelDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelDelete;
    private javax.swing.JComboBox<Collection> jCollections;
    private javax.swing.JButton jDeleteCollection;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * Cài đặt icon
     */
    private void setIcon() {
        ImageIcon icon = new ImageIcon("src/View/TitleIcons/IconCollectionDialog.png");
        this.setIconImage(icon.getImage());
    }

}
